Added scroll to top function to my project
mrbhi/Capstone-Project pull request #1
Opened 2022-10-26 17:05 UTC by mrbhi

2022-10-26 19:06 UTC, aimalamiri requested changes
Hi @mrbhi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The pages are designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
You did a great job! but you can improve your project by following the original design idea, so please try update some parts of your design as mentioned in the comments below. I'm really surprised that such a big project has only 3 git commits, it's highly recommended to commit your code too often (don't worry you're not supposed to change anything about your git commits 😊), and the last point is that on the video you forget to show a part of your code that makes you feel proud.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 19:06 UTC, aimalamiri commented on index.html
> +				<li class="menu-item campaign1"><a href="#" class="menu-link campaign">CC Campaign</a></li>
Good job! but as you know it's part of the core requirements to follow the original design idea, so please make sure to update your nav link colors, sizing, and spacing to match the original design.

![image](https://user-images.githubusercontent.com/34779928/198108632-5c5b7d67-16fe-46d8-9a57-b37ddabbec6a.png)

2022-10-26 19:06 UTC, aimalamiri commented on index.html
> +		</div>
It looks great, but you can improved its design by following the original design as much as possible. So please try to update your background image (I can see a blue picture in your video, but it's not available in the one you deployed), header text sizing and colors.

![image](https://user-images.githubusercontent.com/34779928/198109885-dc38f50f-8ae6-4c86-8e46-f7d1ae116f73.png)

2022-10-26 19:06 UTC, aimalamiri commented on index.html
> +			<ul class="program">
It looks fantastic, but it's highly recommended to use the same background color (image) for your own design, so please try to update this part of your page as well.

![image](https://user-images.githubusercontent.com/34779928/198110939-47e8b6f5-4052-4069-895c-86c057d56a2f.png)

2022-10-26 19:06 UTC, aimalamiri commented on index.html
> +					<p class="speaker-position">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi, quo.</p>
It's good to see the data is coming from JavaScript, but don't you think this part of the commented code is not required anymore?

2022-10-26 19:06 UTC, aimalamiri commented on js/script.js
> +    image: './img/sp1.png',
In your repository the image name extensions are capital `PNG` but you're trying to access lowercase `png`, which is not visible for others. In my side I can't see the images at all.

![image](https://user-images.githubusercontent.com/34779928/198111717-e5f0ce74-781e-4bcd-96a3-f1836ee0732a.png)

2022-10-26 19:06 UTC, aimalamiri commented on index.html
> +			<a class="mb-program" href="#">Join GSASET2023 Submit</a>
Well! don't you think the button should be a little bit smaller and center aligned in horizontal direction? please make sure to fix it.

![image](https://user-images.githubusercontent.com/34779928/198112172-81201b30-d4cd-4027-929a-17f4c74b73cc.png)

2022-10-26 19:06 UTC, aimalamiri commented on about.html
> +			<a class="mail" href="#">info@bhitech.com</a>
Good job! but in here you still need to work on the font-size spacing, and colors a little bit. Kindly make sure to fix it.

![image](https://user-images.githubusercontent.com/34779928/198113175-772518f7-f225-46ac-ba7b-9fbc635616ff.png)

2022-10-27 07:26 UTC, mrbhi commented on about.html
> +			<a class="mail" href="#">info@bhitech.com</a>
Good day, @aimalamiri,
Please kindly help me check through it before submitting it for a second review.
Thanks.

2022-10-27 13:33 UTC, zieeco requested changes
Hi @mrbhi,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 13:33 UTC, zieeco commented on css/index.css
> +    background-color: #272731ad;
- Your background is close but you can adjust it also to be very close to the design. Here's the color 
`background-color: rgba(255, 255, 255, 0.1);`

2022-10-27 13:33 UTC, zieeco commented on css/index.css
> +    background-color: #272731ad;
# VIDEO PRESENTATION

- As it's a requirement you should show a part of your code that you're proud of, please, kindly update the video and show some code from your VSCode editor that you're proud of as requested by the previous reviewer as this is a core requirement to have your project approved. see the image below, the part highlighted in a red line below:

![Screenshot from 2022-10-27 14-23-14](https://user-images.githubusercontent.com/59397159/198298010-45df4323-6621-4dcf-9da1-16bdd0bae72b.png)

---

2022-10-27 16:13 UTC, ShahierNashaat approved these changes
Hi @mrbhi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 16:17 UTC, merged